name: Pizzeria Da Luigi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}

          script: |
            cd /home/ubuntu/Pizzeria-Da-Luigi
            git pull origin main

            cd frontend
            npm install
            npm run build

            sudo rm -rf /var/www/html/*
            sudo cp -r dist/* /var/www/html/